# rocks-config
[config]
auto_setup = true

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks-config.nvim" = "3.1.0"
"rocks-git.nvim" = "2.5.3"
"rocks.nvim" = "2.44.0"
"which-key.nvim" = "3.17.0"
neogit = "2.0.0"
nvim-web-devicons = "0.100"
"oil.nvim" = "2.15.0"
"nvim-colorizer.lua" = "scm"
dashboard-nvim = "scm"
neorg = "9.2.0"
neorg-interim-ls = "2.1.1"
neorg-conceal-wrap = "1.0.1"
neorg-telescope = "1.2.2"
"telescope.nvim" = "scm"
friendly-snippets= "scm"
"auto-save.nvim" = "scm"

[plugins."barbar.nvim"]
git = "romgrk/barbar.nvim"
rev = "v1.9.1"

[plugins.nvim]
git = "catppuccin/nvim"
rev = "v1.9.0"

[plugins."blink.cmp"]
git = "saghen/blink.cmp"
rev = "v0.13.1"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.3"

[plugins.orgmode]
git = "https://github.com/nvim-orgmode/orgmode"
rev = "0.5.2"

[plugins."img-clip.nvim"]
git = "https://github.com/hakonharnes/img-clip.nvim"
rev = "v0.6.0"

